APP_NAME = "STM32 MacroPad Configurator"
APP_VERSION = "0.1.0"
DEFAULT_BAUDRATE = 115200
EXPECTED_SERIAL_NUMBER = "VOID001"
HANDSHAKE_TIMEOUT_S = 1.0
PING_COMMAND = "PING"
PING_RESPONSE = "STM32_MACROPAD_V1"
GET_COMMAND_TEMPLATE = "GET {button}\n"
SET_COMMAND_TEMPLATE = "SET {button} {binding}"
SAVE_COMMAND = "SAVE\r\n"
GETALL_COMMAND = "GETALL\r\n"
MAX_BUTTONS = 4
VALID_MODIFIERS = [
    "CTRL", "SHIFT", "ALT", "WIN",
    "RCTRL", "RSHIFT", "RALT", "RWIN",
]
VALID_KEYS = [
    "A","B","C","D","E","F","G","H","I","J","K","L","M",
    "N","O","P","Q","R","S","T","U","V","W","X","Y","Z",
    "1","2","3","4","5","6","7","8","9","0",
    "ENTER","ESC","BACKSPACE","TAB","SPACE","DELETE","INSERT","HOME","END",
    "PAGEUP","PAGEDOWN","UP","DOWN","LEFT","RIGHT",
    "F1","F2","F3","F4","F5","F6","F7","F8","F9","F10","F11","F12",
    "MINUS","EQUAL","LBRACKET","RBRACKET","BACKSLASH","SEMICOLON","APOSTROPHE",
    "GRAVE","COMMA","DOT","SLASH","CAPSLOCK","NUMLOCK","SCROLLLOCK",
    "KP0","KP1","KP2","KP3","KP4","KP5","KP6","KP7","KP8","KP9",
    "KP_PLUS","KP_MINUS","KP_MULTIPLY","KP_DIVIDE","KP_ENTER","KP_DOT",
    "PRINTSCREEN","PAUSE","MENU",
]
VALID_CONSUMER = [
    "VOLUP", "VOLDOWN", "MUTE", "PLAY", "NEXT", "PREV", "BRIGHTUP", "BRIGHTDOWN",
]
